<?php

namespace Database\Seeders;

use App\Models\CoffeePlace;
use App\Models\User;
use App\Services\MediaService;
use Illuminate\Database\Seeder;

class CoffeePlaceSeeder extends Seeder
{
    /**
     * Seed the coffee places, ported from the Nuxt app's seed_coffeeplaces.ts.
     */
    public function run(): void
    {
        $places = [
            ['name' => 'Floe Coffee & Space', 'address' => 'Jl. Raya Ngawi - Caruban No.KM 2, Nglarangan, Karangasri, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63218', 'description' => 'Kafe modern di pinggiran Kota Ngawi dengan konsep semi-outdoor yang luas dan estetik. Sangat cocok untuk mengerjakan tugas atau sekadar nongkrong santai.', 'lat' => -7.407694141624345, 'lng' => 111.46570697169916, 'mapUrl' => 'https://maps.app.goo.gl/bDB1DoQoiiWzwu7Q6', 'image' => 'floe', 'wifiProvider' => 'Biznet', 'parkFee' => 0, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => false, 'open' => '09:00', 'close' => '23:00'],
            ['name' => 'Kopi Kenangan Ngawi', 'address' => 'Jl. Teuku Umar No.20, Sidorejo, Ketanggi, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63252', 'description' => 'Gerai kopi favorit di pusat Kota Ngawi yang menyajikan pilihan kopi susu kekinian. Cocok untuk dinikmati langsung atau dipesan lewat layanan pesan antar.', 'lat' => -7.401118141102577, 'lng' => 111.44260554509965, 'mapUrl' => 'https://maps.app.goo.gl/veQPetconwQxxWaT9', 'image' => 'kopken-ngawi', 'wifiProvider' => 'Indibiz', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => true, 'open' => '09:00', 'close' => '23:00'],
            ['name' => 'Kopi Kenangan Poins Square Lebak Bulus', 'address' => 'Lt 3 Unit 3F 29, Jl. H. Ilyas No.168, RT.9/RW.7, Lb. Bulus, Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12440', 'description' => 'Gerai kopi praktis yang terletak di Poins Square Mall, Lebak Bulus. Pilihan utama para komuter untuk mendapatkan kopi susu andalan sebelum bepergian.', 'lat' => -6.289337935146352, 'lng' => 106.77823728743105, 'mapUrl' => 'https://maps.app.goo.gl/ssgT1bNwD797ShdMA', 'image' => 'kopken-poins-square', 'wifiProvider' => 'Indibiz', 'parkFee' => 5000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Jakarta Selatan', 'recommended' => true, 'open' => '09:00', 'close' => '23:00'],
            ['name' => 'Kopi Kenangan Madiun', 'address' => 'Jl. Cokroaminoto No.76C, Kejuron, Kec. Taman, Kota Madiun, Jawa Timur 63133', 'description' => 'Gerai kopi susu kekinian di ruko strategis Jalan Cokroaminoto. Menyediakan berbagai menu minuman manis dan kopi khas Kopi Kenangan untuk warga Madiun.', 'lat' => -7.634867431544209, 'lng' => 111.51937105337524, 'mapUrl' => 'https://maps.app.goo.gl/UTayTrLyJbqb9x167', 'image' => 'kopken-madiun', 'wifiProvider' => 'Indibiz', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Madiun', 'recommended' => false, 'open' => '09:00', 'close' => '23:00'],
            ['name' => 'The Real Coffee and Eatery', 'address' => 'Dungus, Karangasri, Ngawi, Ngawi Regency, East Java 63218', 'description' => 'Kafe dan tempat makan dengan menu bervariasi yang berlokasi strategis di Ngawi. Suasana nyaman menjadikannya tempat favorit berkumpul bersama keluarga.', 'lat' => -7.404721230883661, 'lng' => 111.4615439504678, 'mapUrl' => 'https://maps.app.goo.gl/NSEMj2r1KzbNLPFA8', 'image' => 'the-real', 'wifiProvider' => 'Telkom', 'parkFee' => 0, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => false, 'open' => '10:00', 'close' => '23:00'],
            ['name' => 'Adess Pool & Adess Cafe', 'address' => 'Jl. Teuku Umar, Kerek, Margomulyo, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63211', 'description' => 'Tempat ngopi dengan wisata kolam renang yang berdekatan. Cocok untuk bersantai bersama keluarga atau teman, sambil menikmati berbagai pilihan kopi dan makanan ringan.', 'lat' => -7.401708930975215, 'lng' => 111.44213703743462, 'mapUrl' => 'https://maps.app.goo.gl/EV6MEStDMbEUedzEA', 'image' => 'ades-cafe', 'wifiProvider' => 'Telkom', 'parkFee' => 2000, 'price' => 'cheap', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => true, 'open' => '10:00', 'close' => '22:00'],
            ['name' => 'Glory Coffinery', 'address' => 'Jl. Trunojoyo, RT.04/RW.03, Kerek, Margomulyo, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63217', 'description' => 'Glory Coffinery menawarkan suasana yang nyaman dengan pilihan kopi berkualitas. Tempat ini cocok untuk bersantai atau bekerja dengan akses WiFi yang cukup baik.', 'lat' => -7.404868320662563, 'lng' => 111.44049531386896, 'mapUrl' => 'https://maps.app.goo.gl/mFHi4V6NA3aHHcMm8', 'image' => 'glory-coffeenary', 'wifiProvider' => 'Telkom', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => false, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'Portafighter #1 Ngawi', 'address' => 'Jl. Brawijaya No.13, Kerek, Margomulyo, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63271', 'description' => 'Portafighter #1 Ngawi adalah tempat yang cocok untuk para pecinta kopi. Dengan akses WiFi yang memadai dan lokasi yang strategis.', 'lat' => -7.408397476493666, 'lng' => 111.4421515691249, 'mapUrl' => 'https://maps.app.goo.gl/DuK2vPBqSJawYTni7', 'image' => 'porta-1', 'wifiProvider' => 'Telkom', 'parkFee' => 0, 'price' => 'cheap', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => false, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'THX Coffee', 'address' => 'Jl. Ahmad Yani No.5, Beran I, Beran, Kec. Ngawi, Kabupaten Ngawi, Jawa Timur 63216', 'description' => 'THX Coffee menghadirkan suasana yang tenang dengan berbagai pilihan kopi. Kafe ini dilengkapi dengan WiFi yang cukup baik, menjadikannya tempat yang ideal untuk bekerja.', 'lat' => -7.420078593519739, 'lng' => 111.44153738052064, 'mapUrl' => 'https://maps.app.goo.gl/Wfyd2EN5DwRRLmDV9', 'image' => 'thx', 'wifiProvider' => 'Telkom', 'parkFee' => 0, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Ngawi', 'recommended' => false, 'open' => '13:00', 'close' => '22:00'],
            ['name' => 'Ikio Coffee', 'address' => 'Jl. Eka Karya No.1, Mojorejo, Kec. Taman, Kota Madiun, Jawa Timur 63139', 'description' => 'Kafe dengan suasana yang nyaman dan tenang, cocok untuk bekerja atau bersantai dengan teman. Menawarkan berbagai jenis kopi dan makanan ringan.', 'lat' => -7.636885279376751, 'lng' => 111.53253765672265, 'mapUrl' => 'https://maps.app.goo.gl/c1962JA6Yv32Absb8', 'image' => 'ikio', 'wifiProvider' => 'Biznet', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Madiun', 'recommended' => true, 'open' => '08:00', 'close' => '23:00'],
            ['name' => 'Warung Kopi Semilir', 'address' => 'Jl. Letkol Suwarno No.17, Kanigoro, Kec. Kartoharjo, Kota Madiun, Jawa Timur 63118', 'description' => 'Warung Kopi Semilir menawarkan suasana yang nyaman dan sejuk, ideal untuk bersantai sambil menikmati secangkir kopi. Dilengkapi dengan WiFi yang memadai dan bebas biaya parkir.', 'lat' => -7.63678717594058, 'lng' => 111.53988206582551, 'mapUrl' => 'https://maps.app.goo.gl/9EXqVzTGjjcttF637', 'image' => 'semilir-madiun', 'wifiProvider' => 'Telkom', 'parkFee' => 0, 'price' => 'cheap', 'wifiSpeed' => 'medium', 'region' => 'Madiun', 'recommended' => false, 'open' => '08:00', 'close' => '23:59'],
            ['name' => 'Balen Coffee', 'address' => 'Jl. Kemiri No.19, Taman, Kec. Taman, Kota Madiun, Jawa Timur 63118', 'description' => 'Balen Coffee adalah tempat yang nyaman untuk menikmati kopi dengan suasana yang tenang. Dilengkapi dengan WiFi kuat dari Biznet dan tanpa biaya parkir.', 'lat' => -7.636568780590796, 'lng' => 111.52380906969479, 'mapUrl' => 'https://maps.app.goo.gl/BmbTCvdSRCkXrnzAA', 'image' => 'balen-coffee', 'wifiProvider' => 'Biznet', 'parkFee' => 0, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Madiun', 'recommended' => false, 'open' => '09:00', 'close' => '23:00'],
            ['name' => 'The Weekend', 'address' => 'Jl. Tegalgondo No.221A, Wunutsari, Tegalgondo, Kec. Karang Ploso, Kabupaten Malang, Jawa Timur 65152', 'description' => 'The Weekend adalah tempat nongkrong yang nyaman dengan suasana santai dan modern. Menawarkan WiFi yang kuat dari Biznet, sangat cocok untuk bekerja atau bersantai di akhir pekan.', 'lat' => -7.915055950552338, 'lng' => 112.59205980285974, 'mapUrl' => 'https://maps.app.goo.gl/GeMyCKSuLe3akSzt8', 'image' => 'the-weekend', 'wifiProvider' => 'Biznet', 'parkFee' => 0, 'price' => 'expensive', 'wifiSpeed' => 'strong', 'region' => 'Malang', 'recommended' => true, 'open' => '09:00', 'close' => '23:59'],
            ['name' => 'Semusim Cafe', 'address' => 'Jl. MT. Haryono No.110, Ketawanggede, Kec. Lowokwaru, Kota Malang, Jawa Timur 65145', 'description' => 'Kafe populer berkonsep ruang kerja (workspace) yang luas dan nyaman untuk mahasiswa sekitar Lowokwaru. Menyediakan koneksi internet cepat dan harga bersahabat.', 'lat' => -7.947019659957446, 'lng' => 112.6133933353694, 'mapUrl' => 'https://maps.app.goo.gl/iQRcqcYjyTZAiDc67', 'image' => 'semusim', 'wifiProvider' => 'Telkom', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Malang', 'recommended' => true, 'open' => '09:00', 'close' => '02:00'],
            ['name' => 'Kopi Studio 24 Srimaya', 'address' => 'Jl. Balai Desa Kepuharjo, Kedawung, Ngijo, Kec. Karang Ploso, Kabupaten Malang, Jawa Timur 65152', 'description' => 'Kafe ramah kerja (workspace-friendly) 24 jam di area Karang Ploso. Menyediakan tempat yang tenang dengan fasilitas internet stabil untuk bekerja seharian.', 'lat' => -7.912667124019404, 'lng' => 112.61938581487722, 'mapUrl' => 'https://maps.app.goo.gl/ZVRvAZateWPp72uq8', 'image' => 'kopstud-srimaya', 'wifiProvider' => 'Biznet', 'parkFee' => 0, 'price' => 'cheap', 'wifiSpeed' => 'strong', 'region' => 'Malang', 'recommended' => false, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'Kopi Studio 24 Sigura-Gura', 'address' => 'Jl. Sigura - Gura No.33, Karangbesuki, Kec. Sukun, Kota Malang, Jawa Timur 65149', 'description' => 'Workspace dan kedai kopi 24 jam yang terletak strategis di Sigura-Gura. Menjadi andalan mahasiswa untuk belajar kelompok atau mengerjakan tugas malam hari.', 'lat' => -7.962534571994624, 'lng' => 112.61528646943033, 'mapUrl' => 'https://maps.app.goo.gl/ZVRvAZateWPp72uq8', 'image' => 'kopstud-sigura-gura', 'wifiProvider' => 'Biznet', 'parkFee' => 0, 'price' => 'cheap', 'wifiSpeed' => 'strong', 'region' => 'Malang', 'recommended' => true, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'Studio Bakso & Kopi Studio 24 Suhat', 'address' => 'Jl. Soekarno Hatta, Mojolangu, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141', 'description' => 'Kombinasi unik antara warung bakso lezat dan kafe 24 jam di kawasan Soekarno-Hatta. Tempat nongkrong multifungsi yang cocok untuk makan malam sekaligus begadang kerja tugas.', 'lat' => -7.94568223495749, 'lng' => 112.61961240771295, 'mapUrl' => 'https://maps.app.goo.gl/FbaA4hD5rUYSu3hy7', 'image' => 'kopstud-suhat', 'wifiProvider' => 'Biznet', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Malang', 'recommended' => true, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'Warung Kopie Sarkawie', 'address' => 'Jl. Wisnu Wardhana No.25, Candirenggo, Kec. Singosari, Kabupaten Malang, Jawa Timur 65153', 'description' => 'Warung Kopie Sarkawie menawarkan suasana yang nyaman dengan kopi khas lokal. Tempat ini cocok untuk bersantai atau bekerja dengan akses WiFi yang kuat.', 'lat' => -7.885407976176824, 'lng' => 112.66457997979296, 'mapUrl' => 'https://maps.app.goo.gl/NPhLaw7DmR9RKfdi8', 'image' => 'sarkawie-shs', 'wifiProvider' => 'Telkom', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Malang', 'recommended' => false, 'open' => '09:00', 'close' => '22:00'],
            ['name' => 'TWCE Cafe & Eatery', 'address' => 'Sebelah cucian mobil, Jl. Saxophone, Tunggulwulung, Kota Malang, Jawa Timur 65143', 'description' => 'TWCE Cafe & Eatery adalah tempat yang nyaman untuk menikmati berbagai macam makanan dan minuman di Malang. Terletak di area yang strategis, cocok untuk bertemu teman.', 'lat' => -7.926177311423704, 'lng' => 112.60539100204018, 'mapUrl' => 'https://maps.app.goo.gl/7VRdnnMG3ur2HWfj7', 'image' => 'twce-coffee', 'wifiProvider' => 'Telkom', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'medium', 'region' => 'Malang', 'recommended' => true, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'Warkop Antara', 'address' => 'Jl. Saxophone, Tunggulwulung, Kec. Lowokwaru, Kota Malang, Jawa Timur 65143', 'description' => 'Warkop Antara adalah tempat yang ideal untuk menikmati kopi dan suasana yang santai di Malang. Dengan harga terjangkau dan fasilitas WiFi dari Telkom.', 'lat' => -7.924402295940105, 'lng' => 112.60341239239271, 'mapUrl' => 'https://maps.app.goo.gl/tQ4tDSsBQ4L8WwGn6', 'image' => 'antara', 'wifiProvider' => 'Telkom', 'parkFee' => 0, 'price' => 'cheap', 'wifiSpeed' => 'medium', 'region' => 'Malang', 'recommended' => false, 'open' => '00:00', 'close' => '23:59'],
            ['name' => 'SETITI Coffee Shop Klaten', 'address' => 'Jl. Pemuda No.295, Mlinjon, Tonggalan, Kec. Klaten Tengah, Kabupaten Klaten, Jawa Tengah 57412', 'description' => 'SETITI Coffee Shop merupakan tempat yang cocok untuk menikmati kopi dengan suasana yang nyaman di Klaten. Disediakan WiFi dari Biznet dengan kecepatan yang kuat.', 'lat' => -7.713044114964349, 'lng' => 110.59335567416215, 'mapUrl' => 'https://maps.app.goo.gl/kq36wfJNWy2g8xNx6', 'image' => 'setiti', 'wifiProvider' => 'Biznet', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Klaten', 'recommended' => true, 'open' => '08:00', 'close' => '23:00'],
            ['name' => 'Awor Coffee Klaten', 'address' => 'Jl. Merbabu No.5, Gayamprit, Kec. Klaten Sel., Kabupaten Klaten, Jawa Tengah 57412', 'description' => 'Awor Coffee adalah tempat yang tepat untuk menikmati kopi berkualitas dan suasana yang tenang di Klaten. Dengan WiFi dari Biznet dan jam operasional dari pagi hingga malam.', 'lat' => -7.713044114964349, 'lng' => 110.59335567416215, 'mapUrl' => 'https://maps.app.goo.gl/kq36wfJNWy2g8xNx6', 'image' => 'awor-coffee-klt', 'wifiProvider' => 'Biznet', 'parkFee' => 2000, 'price' => 'medium', 'wifiSpeed' => 'strong', 'region' => 'Klaten', 'recommended' => false, 'open' => '08:00', 'close' => '23:00'],
        ];

        $media = app(MediaService::class);
        $userId = User::query()->value('id');

        foreach ($places as $place) {
            CoffeePlace::query()->create([
                'name' => $place['name'],
                'address' => $place['address'],
                'description' => $place['description'],
                'latitude' => $place['lat'],
                'longitude' => $place['lng'],
                'map_url' => $place['mapUrl'],
                'image' => $media->storeFromPublicPath("/images/coffee-shops/{$place['image']}.webp", $userId)->path,
                'wifi_provider' => $place['wifiProvider'],
                'wifi_speed' => $place['wifiSpeed'],
                'price_tier' => $place['price'],
                'park_fee' => $place['parkFee'],
                'opens_at' => $place['open'],
                'closes_at' => $place['close'],
                'region' => $place['region'],
                'is_recommended' => $place['recommended'],
            ]);
        }
    }
}
